name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest
        
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Test imports
      run: |
        python -c "from utils.data_utils import check_dataset_balance; print('✅ Data utils imported')"
        python -c "from utils.imbalance_utils import ImbalanceHandler; print('✅ Imbalance utils imported')"
        python -c "from utils.training_utils import check_system_resources; print('✅ Training utils imported')"
        
    - name: Test scripts
      run: |
        python scripts/01_analyze_data.py --help
        python scripts/02_train_model.py --help

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      run: |
        docker build -t chest-xray-detection:latest .