# Dataset
path: ./data
train: images/train
val: images/val
test: images/test

# Classes
nc: 3
names: ['clavicle_fracture', 'foreign_body_bronchus', 'normal']

# Model
model: yolov8s.pt
weights: yolov8s.pt

# Training
epochs: 50
batch: 16
imgsz: 640
workers: 4
device: 0
patience: 10
save: true
exist_ok: true

# Hyperparameters
lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1

# Augmentation
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0.0