# Легковесная конфигурация для слабого железа
path: ./data
nc: 3
names: ['clavicle_fracture', 'foreign_body_bronchus', 'normal']

model: yolov8n.pt
imgsz: 416
batch: 8
workers: 2
device: 0

epochs: 30
patience: 5
lr0: 0.001

# Упрощенная аугментация
mosaic: 0.5
mixup: 0.0
perspective: 0.0